name: App Store Production

trigger: master

pool:
  vmImage: 'macos-latest'

variables:
- group: Mobile-Applications-Key-Vault
- group: ios-development

steps:
- script: /usr/local/bin/carthage update --platform ios
  displayName: 'Install frameworks with Carthage'
- script: |
   export FASTLANE_USER=$(APPLE-ITUNES-CONNECT-USER)
   export FASTLANE_PASSWORD="$(APPLE-ITUNES-CONNECT-PASSWORD)"

   fastlane appstore_release team_id:"$(APPLE-DEVELOPER-PORTAL-APPSTORE-TEAMID)" app_identifier:"$(BUNDLE-IDENTIFIER)"
  displayName: 'Deploying to Apple App Store'
  